#!/bin/bash

set -euo pipefail

echo "building quorum-aws locally"
stack setup
stack build

echo "building istanbul-tools locally"
make -C ./dependencies/go/src/github.com/istanbul-tools

echo "building quorum-aws for AWS"
docker build -t quorum-aws .

echo "building quorum"
docker build -t quorum ./dependencies/quorum

echo "building constellation"
docker build -t constellation -f ./dependencies/constellation/build-fedora.dockerfile --build-arg DISTRO_VERSION=26 ./dependencies/constellation

echo "done building packages"
