resolver: nightly-2017-11-01 # for ghc 8.2

packages:
- '.'
- location:
    git: https://github.com/jpmorganchase/quorum-tools.git
    commit: fe76791a6d49a5b5ea82566e6ce12acfdc3e0d06
  extra-dep: true
#
# FIXME: duplicated from quorum-tools:
#
- location:
    git: https://github.com/jpmorganchase/constellation.git
    commit: 14997fbb8d5ae0b2db6ea182fcabad5d69ed7b23
  extra-dep: true

#
# FIXME: duplicated from quorum-tools:
#
extra-deps:
- uri-bytestring-0.2.3.3
- foldl-1.2.5
- turtle-1.3.6
- symmetric-properties-0.1.0.0
- rate-limit-1.1.1
- time-units-1.0.0
- aeson-1.1.2.0
- BerkeleyDB-0.8.7        # constellation
- logging-3.0.4           # constellation
- saltine-0.1.0.0         # constellation
- cryptonite-0.24         # constellation

flags: {}

extra-package-dbs: []
